### ISSUE TITLE
Implement deployment checker

### ISSUE THREAD

**Issue by maxbischoff** [Comcast/kuberhealthy#154]
**Describe the solution you would like to see happen**
A check for Deployments analogous to the existing DaemonSet check would be useful to verify, that the Controller Manager loops for Deployments and ReplicaSet are still working. As most applications utilize Deployments, it is important to be sure, that this functionality is working.

**How do you propose we build it?**
The check could be built similar to the existing check for daemon set, but using a Deployment instead of a DaemonSet. One replica would be enough for this check, as the DaemonSet check already verifies, that pods can be scheduled on all nodes.

What is your opinion on deployment checks? Would you accept contributions for such a check?

**Comment by lolimjake** [comment]
I think this is reasonable if its implemented very similarly to the DS checker as you said.  It would be low impact and have very low resource requirements. 

We'd like to test most commonly used kube features eventually and this fits into that plan.  If @integrii and @ihoegen agree, I'd say we accept this proposal.

**Comment by integrii** [comment]
I think this is a useful thing to test, but I am not sure it should be enabled by default.  We are already asking a lot of cluster operators with the daemonset checker and the deployment overlaps a good bit.

Be sure that you include the proper flags and environment variables in `main.go` so that it can be toggled like the other checks (as of recently).  The helm chart and static spec files would need an update, too...

**Comment by integrii** [comment]
I also am a little sad that [this issue](https://github.com/Comcast/kuberhealthy/issues/143) has not yet been completed.  I would have liked to fold this into a more generic test creation pattern instead of the very static one we have today.
