### ISSUE TITLE
Update pause image to 3.1

### ISSUE THREAD

**Issue by everflux** [Comcast/kuberhealthy#167]
**Describe the feature you would like and why you want it**
The pause image used in the daemonset-test is currently  gcr.io/google_containers/pause:0.8.0  which is an AMD64 image. A change to gcr.io/google_containers/pause:3.1 would work on all architectures supported by kubernetes.

**Additional context**
This is related to https://github.com/Comcast/kuberhealthy/issues/166

**Comment by integrii** [comment]
They original choice here was to use the same pause container that kubelet used because it would be cached. Because that image changes with different versions, we should probably just assume that it is possible to download the pause container from the web...

We want to be careful not to break anyone currently using an "offline" cluster, though.  We may want to make this configurable, with a default to the latest version.

If we do make this configurable, it is probably best to stop and setup a configmap driven config file that is read and watched for changes in real time...

**Comment by everflux** [comment]
That choice sounds perfectly reasonable, though in my case it did not use the desired default image, that would have been the pause 3.1 image which is available for arm64. (I am using crio as container runtime and configured the pause image to use pause:3.1

```
grep pause /etc/crio/crio.conf 
pause_image = "k8s.gcr.io/pause:3.1"
```

For kubelet I did not configure a special infra image, according to the manual it should default to pause:3.1 (at least for kubernetes 1.14.1 which I am using)

```
--pod-infra-container-image string
The image whose network/ipc namespaces containers 
in each pod will use. (default `"k8s.gcr.io/pause:3.1")`
```

**Comment by lolimjake** [comment]
Ah, the pause container image is already configurable with the `dsPauseContainerImageOverride` flag, though the default is currently `gcr.io/google_containers/pause:0.8.0`.  Full flag documentation is available here: https://github.com/Comcast/kuberhealthy/blob/master/docs/FLAGS.md.  

I think it's fine to update the default pause container to 3.1 and will work that change into the next release (coming soon™).
