### ISSUE TITLE
Implement node functionality checker that deploys a pod to every available node in the cluster

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#186]
Cordoned nodes are used when the daemonset checker's daemonset is deployed.  We should always ignore cordoned nodes because they are likely known to be bad.

We should modify the daemonset checker spec to have a node anti-affinity policy (or otherwise) to achieve this behavior.

**Comment by rukatm** [comment]
From https://kubernetes.io/docs/concepts/architecture/nodes/

> Note: Pods created by a DaemonSet controller bypass the Kubernetes scheduler and do not respect the unschedulable attribute on a node. This assumes that daemons belong on the machine even if it is being drained of applications while it prepares for a reboot.

**Comment by integrii** [comment]
Whoa.  Thanks for finding this.  I wonder if we need to move the checker to _not_ be a daemonset in order to get the functionality we want...

**Comment by joshulyne** [comment]
https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#taints-and-tolerations
^^ this lists out the tolerations automatically added to the daemonset and it includes the `node.kubernetes.io/unschedulable:NoSchedule` toleration. 

Instead of rewriting the daemonset checker, we should consider writing a new khcheck that verifies pods are scheduled on everything except cordoned nodes.

**Comment by integrii** [comment]
looks like we can't prevent this.  Changing to a new issue for adding a new node functionality check
