### ISSUE TITLE
Retain completed/failed pods for historical reasons

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#265]
We need to leave completed/failed pods around for awhile so that admins can look at them for log information.  Currently, when a check fails, it gets deleted and re-created on next run.  This drops all history for it, so we don't normally know what went wrong on the checker pod.

We should:
- make each check run have a unique pod name
- leave some number of pods in history around for diagnostics even if completed/failed
- write a reaper to delete checker pods that are no longer useful

**Additional context**
Perhaps making the history number configurable like with cron jobs would be a good help.

**Comment by joshulyne** [comment]
Additional suggestions:
- We should consider leaving around failed pods for a while longer than completed pods. Since some checks run at a much faster interval, leaving some number of pods in history might not be enough time for kube operators to find/check the failed checker pod. 
- Include the actual checker pod name in the json status page -- could replace the `AuthoritativePod` field with the checker pod name for that run -- that way if any failures do occur, kube operators can immediately look into the logs of the checker pod where failures happened.

**Comment by integrii** [comment]
https://github.com/Comcast/kuberhealthy/tree/unique-pod-names is WIP in this.  I added the eviction of pods in place of deletion and made every checker pod use a unique name.

This still needs some kind of daemon running either in the external checker or in the main kuberhealthy program that will appropriately delete completed, failed, or evicted pods after they have reached some limit on count or time.

**Comment by joshulyne** [comment]
Issue addressed in version 2.1.0rc1
