### ISSUE TITLE
DaemonSetChecker is failing 

### ISSUE THREAD

**Issue by janavenkat** [Comcast/kuberhealthy#300]
**Describe the bug**
DaemonSetChecker is failing because of insufficient permission for the user

**Steps To Reproduce**
Apply the YAML from v2.1.0
Check DaemonSetChecker pod logs 

**Expected behavior**
insufficient permission for the user

**Screenshots**

<img width="748" alt="Screenshot 2020-02-06 at 12 15 31" src="https://user-images.githubusercontent.com/28565699/73932513-cbf31f80-48da-11ea-9307-a9330c4d4a38.png">

<img width="1744" alt="Screenshot 2020-02-06 at 12 15 53" src="https://user-images.githubusercontent.com/28565699/73932536-d7dee180-48da-11ea-80d3-1a7c10e2ad57.png">

**Versions**
 - Cluster OS: Ubuntu 18.04
 - Kubernetes Version: 1.11
 - Kuberhealthy Release or build [v2.1.0]

**Comment by integrii** [comment]
Hey there.  What specs did you use to apply your checks.  Were there any errors when that happened?

It looks like the daemonset checker pod can't fetch a list of pods using its service account.

**Comment by janavenkat** [comment]
> Hey there. What specs did you use to apply your checks. Were there any errors when that happened?
I just used this https://raw.githubusercontent.com/Comcast/kuberhealthy/master/deploy/kuberhealthy.yaml 

> It looks like the daemonset checker pod can't fetch a list of pods using its service account.
yes

**Comment by integrii** [comment]
I see.  The only question is how long ago you applied that spec, then.  What KH image are you running?  `kubectl get deployment kuberhealthy -n kuberhealthy -o yaml | grep image:`

I just want to make sure this isn't a problem with our specs for some people.  I know that you can fix the issue by adding a new role binding for the daemonset checker service account.

**Comment by janavenkat** [comment]
> I see. The only question is how long ago you applied that spec, then. What KH image are you running? `kubectl get deployment kuberhealthy -n kuberhealthy -o yaml | grep image:`
> 
> I just want to make sure this isn't a problem with our specs for some people. I know that you can fix the issue by adding a new role binding for the daemonset checker service account.

 image: quay.io/comcast/kuberhealthy:2.1.0

Yes, I can do the role binding for my own but why it's not working for default?

**Comment by janavenkat** [comment]
@integrii I see that there is already  service account for daemonset checker

**Comment by vishalud** [comment]
I've ran into the same issue as mentioned above 

```MBP15-2:~ otadmin$ kubectl get deployment kuberhealthy -n kuberhealthy -o yaml | grep image
        image: quay.io/comcast/kuberhealthy:2.1.0
       ```

**Comment by zeleena** [comment]
Can we reopen this? Unfortunately the change in #305  does not work for me.

The daemonset checker still has insufficient permissions, but incorrectly reports "success" to the status page. So it "appears" to work, but logs indicate the resources were never created/deleted because of insufficient permissions on the `kuberhealthy-daemonset-khcheck` ClusterRole.

Here are the logs:
![kuberhealthy-daemonsetcheck-permissions](https://user-images.githubusercontent.com/12972510/74970642-b9094080-53ec-11ea-8d20-4832e0cd7e29.png)

A fix for this would be to add `apps` to `apiGroups`, `daemonsets` to `resources`, and `create` and `delete` to `verbs`. I'm asking for this change so that I can use the helm chart. If there is a different way I should be using this, let me know.

Other details:
* Using the updates from #305  and #315 that were merged today (2/20/2020)
* Kuberhealthy v2.1.2
* Daemonset check v2.0.1
* Cluster OS: Ubuntu 18.04

**Comment by integrii** [comment]
Thanks for bringing this up and trying out the new fixes.  

Are you running your daemonset checker in the `kuberhealthy` namespace?  The RBAC in our spec files describe a `ds-admin` role in the `kuberhealthy` namespace which is attached to the daemonset checker.  That `ds-admin` role has the permissions you describe on it and should be set in your `khcheck` as the service account for the daemonset checker.

https://github.com/Comcast/kuberhealthy/blob/master/deploy/kuberhealthy.yaml#L206

And just to be clear: The best way to apply specs right now is to use the helm chart in this repository (under `deploy/`) or via the flat files linked in the readme.

**Comment by zeleena** [comment]
Yes, the daemonset checker in running in the `kuberhealthy` namespace.

Thanks for pointing out the `ds-admin` role. Then, I believe the issue/fix is that on [Line 216](https://github.com/Comcast/kuberhealthy/blob/master/deploy/kuberhealthy.yaml#L216) the apiGroup should be `apps`, not `app`.

I just made this change locally and it worked for me (the logs reflected going through a successful daemonset check).

Thanks for the clarification. Wanted to mention I had the latest updates. Due to the configuration of my cluster, I need to make some changes to the flat files, which are also not currently configurable in the values of the helm chart either. I was going to make a PR to address these so that my team can use the helm chart (such as adding a `nodeSelector` value and envvars for `KH_EXTERNAL_REPORTING_URL`), and I see that there is a [PR out for allowing non-hardcoded images](https://github.com/Comcast/kuberhealthy/pull/314/files) which we also need. With those changes, my team could use the helm chart, and we'd like to 🙂

**Comment by integrii** [comment]
I just submitted PR #318 for fixing that typo you called out...
